export const workExperience = [
  {
    icon: "A",
    company: "Punch-IN system",
    role: "API-Gateway, Lambda, DynamoDB, S3",
    shortdesc:
      "",
    desc: "A Full-stack web application to learn AWS serverless services such as lambda, API gateway etc. This is a simple application that enables punch in attendence and records the time and date of punch stores it on s3 bucket",
    bgColor: "bg-blue-700",
    textColor: "text-white",
    sourceCode: "https://github.com/Asta1984/AWS-kiminarimas.git",
    webLink: "https://aws-kiminarimas.vercel.app/",
  },
  {
    icon: "P",
    company: "Pokedex",
    role: "React, typeScript, EC2, AXIOS ",
    shortdesc:
      "",
    desc: "A Full-stack web application to view pokemon. Backend is hosted on EC2 with reverse proxy uning NGINX",
    bgColor: "bg-purple-700",
    textColor: "text-white",
    sourceCode: "https://github.com/Asta1984/pokemon_super-engine.git",
    webLink: "https://pokemon-super-engine.vercel.app/",
  },
  {
    icon: "D",
    company: "D-PAY",
    role: "React, Tailwind, typeScript, Solana",
    shortdesc:
      "",
    desc: "A payment gateway that enables the merchent to recieve payment though solana Blockchain in USDC irrespective of the token",
    bgColor: "bg-cyan-700",
    textColor: "text-white",
    sourceCode: "https://github.com/Asta1984/verbose-eureka.git",
    webLink: "https://verbose-eureka-two.vercel.app/",
  },  
    {
    icon: "C",
    company: "C L I N I K 360",
    role: "React, Tailwind, typeScript, shadcn",
    shortdesc:
      "",
    desc: "An Full-stack plateform for the Doctors and Patient.",
    bgColor: "bg-red-700",
    textColor: "text-white",
    sourceCode: "https://github.com/Asta1984/360clinikfrontendscaling-fiesta",
    webLink: "https://360clinikfrontendscaling-fiesta-juzx.vercel.app/",
  },  
  {
    icon: "V",
    company: "V4Fluffy",
    role: "React, Tailwind, typeScript, Solana",
    shortdesc:
      "",
    desc: "This a presale landing page, done as a interview task consist of solanawallet adapter and react components",
    bgColor: "bg-teal-700",
    textColor: "text-white",
    sourceCode: "https://github.com/Asta1984/fluffy-octo-invention.git",
    webLink: "https://fluffy-octo-invention-five.vercel.app/",
  },
  {
      icon: "M",
      company: "MoonEX",
      role: "React, Tailwind, typeScript, Shadcn",
      shortdesc:
        "",
      desc: "This a DEX(decentralize exchange) landing page, done for moonex DEX showcasing proficiency in respective tech-stack.",
      bgColor: "bg-green-500",
      textColor: "text-white",
      sourceCode: "https://github.com/Asta1984/stunning-sniffle.git",
      webLink: "https://stunning-sniffle-two.vercel.app/",
    },
    {
      icon: "A",
      company: "Allen Institute",
      role: "React, Tailwind, Javascript, GitHub",
      shortdesc:
        "Allen.in Landing Page",
      desc: "Learning is easy when you do it while building projects, This is a simple edTech landing page.",
      bgColor: "bg-orange-600",
      textColor: "text-white",
      sourceCode: "https://github.com/Asta1984/probable-guacamole.git",
      webLink: "https://allen.sewantika.com/",
    },
    {
      icon: "S",
      company: "Sewantika",
      role: "Javascript, Ejs, DoM , SCSS",
      shortdesc:
        "Landing page for a project",
      desc: " A holistic solution for all problemn related to complete product developemt from ideation, curation, fabrication to market delivery.",
      bgColor: "bg-purple-600",
      textColor: "text-white",
      sourceCode: "",
      webLink: "https://www.sewantika.com/",
    },
    {
      icon: "I",
      company: "Intruder Detection",
      role: "OpenCV, Python",
      shortdesc: "Motion detection using matrix difference",
      desc: "A Python-based motion detection script using OpenCV designed for security systems. The script captures video from the webcam, detects motion, and triggers an audible alarm when motion is detected.",
      bgColor: "bg-green-500",
      textColor: "text-slate-100",
      sourceCode: "https://github.com/Asta1984/Motion-Detection-using-openCV.git",
      webLink: "",
    },
    {
      icon: "P",
      company: "Mordern Perodic table",
      role: "HTML, CSS, Javascript",
      shortdesc: "My first web development project",
      desc: "The idea was simple I could not remember the periodic table at school which push me to learn web dev and built this project.",
      bgColor: "bg-gray-400",
      textColor: "text-white",
      sourceCode: "https://github.com/Asta1984/Periodic-table.git",
      webLink: "https://asta1984.github.io/Periodic-table/",
    },
    {
      icon: "G",
      company: "GangChat",
      role: "Javascript, React, Firebase",
      shortdesc: "A chatroom for close group of friends.",
      desc: "A custom chatroom with firebase backend, authentication and without using web sockets.",
      bgColor: "bg-orange-600",
      textColor: "text-white",
      sourceCode: "https://github.com/Asta1984/gangCHAT.git",
      webLink: "https://gang-chat.vercel.app/",
    },
    {
      icon: "A",
      company: "Autonomous Bot",
      role: "Embedded C, ROS2, SLAM",
      shortdesc: "An autonoumous navigating bot.",
      desc: "Developed and designed a bot capable of multi-terrain operation with 4 degree of freedom uses different sensor fusion to get surrounding data to create 3-D mappings.",
      bgColor: "bg-green-500",
      textColor: "text-white",
      sourceCode: "https://drive.google.com/drive/folders/1JuOScmxXXVIyU6GKKZA9AB_qh4qN3A68",
      webLink: "",
    },
    {
      icon: "T",
      company: "Vehicle Side Profiling",
      role: "Python, UDP, Sensor-fusion",
      shortdesc: "Create side profiles of moving vehicles.",
      desc: "This project involved generation of side profile of vehicle while it's passing through a beam of sensor.",
      bgColor: "bg-red-600",
      textColor: "text-white",
      sourceCode: "",
      webLink: "https://portfolio-website-five-amber.vercel.app/#portfolio",
    },
  ];